# Database Configuration Template
# Copy this file to database.properties and fill in your actual credentials
# DO NOT commit database.properties to version control!

db.url=jdbc:mysql://bdlab04p3.clcmykqu8lqs.us-east-1.rds.amazonaws.com:3306/bdLab04
db.user=admin
db.password=FazazelDB75.
