//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontVR.GestionLentesWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class aplicacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int aplicacionIdField;
        
        private categoriaAplicacion categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string desarrolladorField;
        
        private string descripcionField;
        
        private System.DateTime fechaLanzamientoField;
        
        private bool fechaLanzamientoFieldSpecified;
        
        private string nombreField;
        
        private string rutaInstaladorField;
        
        private double tamanoMBField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int aplicacionId {
            get {
                return this.aplicacionIdField;
            }
            set {
                this.aplicacionIdField = value;
                this.RaisePropertyChanged("aplicacionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public categoriaAplicacion categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string desarrollador {
            get {
                return this.desarrolladorField;
            }
            set {
                this.desarrolladorField = value;
                this.RaisePropertyChanged("desarrollador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaLanzamiento {
            get {
                return this.fechaLanzamientoField;
            }
            set {
                this.fechaLanzamientoField = value;
                this.RaisePropertyChanged("fechaLanzamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaLanzamientoSpecified {
            get {
                return this.fechaLanzamientoFieldSpecified;
            }
            set {
                this.fechaLanzamientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaLanzamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string rutaInstalador {
            get {
                return this.rutaInstaladorField;
            }
            set {
                this.rutaInstaladorField = value;
                this.RaisePropertyChanged("rutaInstalador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double tamanoMB {
            get {
                return this.tamanoMBField;
            }
            set {
                this.tamanoMBField = value;
                this.RaisePropertyChanged("tamanoMB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public enum categoriaAplicacion {
        
        /// <remarks/>
        EDUCATIVA,
        
        /// <remarks/>
        ENTRETENIMIENTO,
        
        /// <remarks/>
        TERAPEUTICA,
        
        /// <remarks/>
        ENTRENAMIENTO,
        
        /// <remarks/>
        PRODUCTIVIDAD,
        
        /// <remarks/>
        SIMULACION,
        
        /// <remarks/>
        MULTIMEDIA,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", ConfigurationName="GestionLentesWS.AplicacionWS")]
    public interface AplicacionWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/obtenerAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/obtenerAplicacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.GestionLentesWS.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/obtenerAplicacion/Fault/Exception" +
            "", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.GestionLentesWS.obtenerAplicacionResponse obtenerAplicacion(FrontVR.GestionLentesWS.obtenerAplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/obtenerAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/obtenerAplicacionResponse")]
        System.Threading.Tasks.Task<FrontVR.GestionLentesWS.obtenerAplicacionResponse> obtenerAplicacionAsync(FrontVR.GestionLentesWS.obtenerAplicacionRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.GestionLentesWS.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacion/Fault/Exceptio" +
            "n", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.GestionLentesWS.eliminarAplicacionResponse eliminarAplicacion(FrontVR.GestionLentesWS.eliminarAplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionResponse")]
        System.Threading.Tasks.Task<FrontVR.GestionLentesWS.eliminarAplicacionResponse> eliminarAplicacionAsync(FrontVR.GestionLentesWS.eliminarAplicacionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.GestionLentesWS.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacion/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.GestionLentesWS.listarAplicacionResponse listarAplicacion(FrontVR.GestionLentesWS.listarAplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionResponse")]
        System.Threading.Tasks.Task<FrontVR.GestionLentesWS.listarAplicacionResponse> listarAplicacionAsync(FrontVR.GestionLentesWS.listarAplicacionRequest request);
        
        // CODEGEN: Parameter 'elemento' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/actualizarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/actualizarAplicacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.GestionLentesWS.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/actualizarAplicacion/Fault/Except" +
            "ion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.GestionLentesWS.actualizarAplicacionResponse actualizarAplicacion(FrontVR.GestionLentesWS.actualizarAplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/actualizarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/actualizarAplicacionResponse")]
        System.Threading.Tasks.Task<FrontVR.GestionLentesWS.actualizarAplicacionResponse> actualizarAplicacionAsync(FrontVR.GestionLentesWS.actualizarAplicacionRequest request);
        
        // CODEGEN: Parameter 'elemento' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/registrarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/registrarAplicacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.GestionLentesWS.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/registrarAplicacion/Fault/Excepti" +
            "on", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.GestionLentesWS.registrarAplicacionResponse registrarAplicacion(FrontVR.GestionLentesWS.registrarAplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/registrarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/registrarAplicacionResponse")]
        System.Threading.Tasks.Task<FrontVR.GestionLentesWS.registrarAplicacionResponse> registrarAplicacionAsync(FrontVR.GestionLentesWS.registrarAplicacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAplicacion", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerAplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerAplicacionRequest() {
        }
        
        public obtenerAplicacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAplicacionResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerAplicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.GestionLentesWS.aplicacion @return;
        
        public obtenerAplicacionResponse() {
        }
        
        public obtenerAplicacionResponse(FrontVR.GestionLentesWS.aplicacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAplicacion", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class eliminarAplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarAplicacionRequest() {
        }
        
        public eliminarAplicacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAplicacionResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class eliminarAplicacionResponse {
        
        public eliminarAplicacionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAplicacion", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarAplicacionRequest {
        
        public listarAplicacionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAplicacionResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarAplicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.GestionLentesWS.aplicacion[] @return;
        
        public listarAplicacionResponse() {
        }
        
        public listarAplicacionResponse(FrontVR.GestionLentesWS.aplicacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarAplicacion", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class actualizarAplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.GestionLentesWS.aplicacion elemento;
        
        public actualizarAplicacionRequest() {
        }
        
        public actualizarAplicacionRequest(FrontVR.GestionLentesWS.aplicacion elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarAplicacionResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class actualizarAplicacionResponse {
        
        public actualizarAplicacionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarAplicacion", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class registrarAplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.GestionLentesWS.aplicacion elemento;
        
        public registrarAplicacionRequest() {
        }
        
        public registrarAplicacionRequest(FrontVR.GestionLentesWS.aplicacion elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarAplicacionResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class registrarAplicacionResponse {
        
        public registrarAplicacionResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AplicacionWSChannel : FrontVR.GestionLentesWS.AplicacionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AplicacionWSClient : System.ServiceModel.ClientBase<FrontVR.GestionLentesWS.AplicacionWS>, FrontVR.GestionLentesWS.AplicacionWS {
        
        public AplicacionWSClient() {
        }
        
        public AplicacionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AplicacionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AplicacionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AplicacionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.GestionLentesWS.obtenerAplicacionResponse FrontVR.GestionLentesWS.AplicacionWS.obtenerAplicacion(FrontVR.GestionLentesWS.obtenerAplicacionRequest request) {
            return base.Channel.obtenerAplicacion(request);
        }
        
        public FrontVR.GestionLentesWS.aplicacion obtenerAplicacion(int id) {
            FrontVR.GestionLentesWS.obtenerAplicacionRequest inValue = new FrontVR.GestionLentesWS.obtenerAplicacionRequest();
            inValue.id = id;
            FrontVR.GestionLentesWS.obtenerAplicacionResponse retVal = ((FrontVR.GestionLentesWS.AplicacionWS)(this)).obtenerAplicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.GestionLentesWS.obtenerAplicacionResponse> FrontVR.GestionLentesWS.AplicacionWS.obtenerAplicacionAsync(FrontVR.GestionLentesWS.obtenerAplicacionRequest request) {
            return base.Channel.obtenerAplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.GestionLentesWS.obtenerAplicacionResponse> obtenerAplicacionAsync(int id) {
            FrontVR.GestionLentesWS.obtenerAplicacionRequest inValue = new FrontVR.GestionLentesWS.obtenerAplicacionRequest();
            inValue.id = id;
            return ((FrontVR.GestionLentesWS.AplicacionWS)(this)).obtenerAplicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.GestionLentesWS.eliminarAplicacionResponse FrontVR.GestionLentesWS.AplicacionWS.eliminarAplicacion(FrontVR.GestionLentesWS.eliminarAplicacionRequest request) {
            return base.Channel.eliminarAplicacion(request);
        }
        
        public void eliminarAplicacion(int id) {
            FrontVR.GestionLentesWS.eliminarAplicacionRequest inValue = new FrontVR.GestionLentesWS.eliminarAplicacionRequest();
            inValue.id = id;
            FrontVR.GestionLentesWS.eliminarAplicacionResponse retVal = ((FrontVR.GestionLentesWS.AplicacionWS)(this)).eliminarAplicacion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.GestionLentesWS.eliminarAplicacionResponse> FrontVR.GestionLentesWS.AplicacionWS.eliminarAplicacionAsync(FrontVR.GestionLentesWS.eliminarAplicacionRequest request) {
            return base.Channel.eliminarAplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.GestionLentesWS.eliminarAplicacionResponse> eliminarAplicacionAsync(int id) {
            FrontVR.GestionLentesWS.eliminarAplicacionRequest inValue = new FrontVR.GestionLentesWS.eliminarAplicacionRequest();
            inValue.id = id;
            return ((FrontVR.GestionLentesWS.AplicacionWS)(this)).eliminarAplicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.GestionLentesWS.listarAplicacionResponse FrontVR.GestionLentesWS.AplicacionWS.listarAplicacion(FrontVR.GestionLentesWS.listarAplicacionRequest request) {
            return base.Channel.listarAplicacion(request);
        }
        
        public FrontVR.GestionLentesWS.aplicacion[] listarAplicacion() {
            FrontVR.GestionLentesWS.listarAplicacionRequest inValue = new FrontVR.GestionLentesWS.listarAplicacionRequest();
            FrontVR.GestionLentesWS.listarAplicacionResponse retVal = ((FrontVR.GestionLentesWS.AplicacionWS)(this)).listarAplicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.GestionLentesWS.listarAplicacionResponse> FrontVR.GestionLentesWS.AplicacionWS.listarAplicacionAsync(FrontVR.GestionLentesWS.listarAplicacionRequest request) {
            return base.Channel.listarAplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.GestionLentesWS.listarAplicacionResponse> listarAplicacionAsync() {
            FrontVR.GestionLentesWS.listarAplicacionRequest inValue = new FrontVR.GestionLentesWS.listarAplicacionRequest();
            return ((FrontVR.GestionLentesWS.AplicacionWS)(this)).listarAplicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.GestionLentesWS.actualizarAplicacionResponse FrontVR.GestionLentesWS.AplicacionWS.actualizarAplicacion(FrontVR.GestionLentesWS.actualizarAplicacionRequest request) {
            return base.Channel.actualizarAplicacion(request);
        }
        
        public void actualizarAplicacion(FrontVR.GestionLentesWS.aplicacion elemento) {
            FrontVR.GestionLentesWS.actualizarAplicacionRequest inValue = new FrontVR.GestionLentesWS.actualizarAplicacionRequest();
            inValue.elemento = elemento;
            FrontVR.GestionLentesWS.actualizarAplicacionResponse retVal = ((FrontVR.GestionLentesWS.AplicacionWS)(this)).actualizarAplicacion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.GestionLentesWS.actualizarAplicacionResponse> FrontVR.GestionLentesWS.AplicacionWS.actualizarAplicacionAsync(FrontVR.GestionLentesWS.actualizarAplicacionRequest request) {
            return base.Channel.actualizarAplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.GestionLentesWS.actualizarAplicacionResponse> actualizarAplicacionAsync(FrontVR.GestionLentesWS.aplicacion elemento) {
            FrontVR.GestionLentesWS.actualizarAplicacionRequest inValue = new FrontVR.GestionLentesWS.actualizarAplicacionRequest();
            inValue.elemento = elemento;
            return ((FrontVR.GestionLentesWS.AplicacionWS)(this)).actualizarAplicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.GestionLentesWS.registrarAplicacionResponse FrontVR.GestionLentesWS.AplicacionWS.registrarAplicacion(FrontVR.GestionLentesWS.registrarAplicacionRequest request) {
            return base.Channel.registrarAplicacion(request);
        }
        
        public void registrarAplicacion(FrontVR.GestionLentesWS.aplicacion elemento) {
            FrontVR.GestionLentesWS.registrarAplicacionRequest inValue = new FrontVR.GestionLentesWS.registrarAplicacionRequest();
            inValue.elemento = elemento;
            FrontVR.GestionLentesWS.registrarAplicacionResponse retVal = ((FrontVR.GestionLentesWS.AplicacionWS)(this)).registrarAplicacion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.GestionLentesWS.registrarAplicacionResponse> FrontVR.GestionLentesWS.AplicacionWS.registrarAplicacionAsync(FrontVR.GestionLentesWS.registrarAplicacionRequest request) {
            return base.Channel.registrarAplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.GestionLentesWS.registrarAplicacionResponse> registrarAplicacionAsync(FrontVR.GestionLentesWS.aplicacion elemento) {
            FrontVR.GestionLentesWS.registrarAplicacionRequest inValue = new FrontVR.GestionLentesWS.registrarAplicacionRequest();
            inValue.elemento = elemento;
            return ((FrontVR.GestionLentesWS.AplicacionWS)(this)).registrarAplicacionAsync(inValue);
        }
    }
}
