//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontVR.DispositivosWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class grupo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private dispositivo[] dispositivosField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int grupoIdField;
        
        private string nombreField;
        
        private usuario responsableField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dispositivos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public dispositivo[] dispositivos {
            get {
                return this.dispositivosField;
            }
            set {
                this.dispositivosField = value;
                this.RaisePropertyChanged("dispositivos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int grupoId {
            get {
                return this.grupoIdField;
            }
            set {
                this.grupoIdField = value;
                this.RaisePropertyChanged("grupoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public usuario responsable {
            get {
                return this.responsableField;
            }
            set {
                this.responsableField = value;
                this.RaisePropertyChanged("responsable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class dispositivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private aplicacion[] aplicacionesInstaladasField;
        
        private configuracion[] configuracionesField;
        
        private int dispositivoIdField;
        
        private estadoConexion estadoConexionField;
        
        private bool estadoConexionFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private firmware firmwareActualField;
        
        private grupo grupoField;
        
        private string modeloField;
        
        private int nivelBateriaField;
        
        private string nombreField;
        
        private string numeroSerieField;
        
        private string ubicacionField;
        
        private System.DateTime ultimaConexionField;
        
        private bool ultimaConexionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aplicacionesInstaladas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public aplicacion[] aplicacionesInstaladas {
            get {
                return this.aplicacionesInstaladasField;
            }
            set {
                this.aplicacionesInstaladasField = value;
                this.RaisePropertyChanged("aplicacionesInstaladas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("configuraciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public configuracion[] configuraciones {
            get {
                return this.configuracionesField;
            }
            set {
                this.configuracionesField = value;
                this.RaisePropertyChanged("configuraciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int dispositivoId {
            get {
                return this.dispositivoIdField;
            }
            set {
                this.dispositivoIdField = value;
                this.RaisePropertyChanged("dispositivoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public estadoConexion estadoConexion {
            get {
                return this.estadoConexionField;
            }
            set {
                this.estadoConexionField = value;
                this.RaisePropertyChanged("estadoConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoConexionSpecified {
            get {
                return this.estadoConexionFieldSpecified;
            }
            set {
                this.estadoConexionFieldSpecified = value;
                this.RaisePropertyChanged("estadoConexionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public firmware firmwareActual {
            get {
                return this.firmwareActualField;
            }
            set {
                this.firmwareActualField = value;
                this.RaisePropertyChanged("firmwareActual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public grupo grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
                this.RaisePropertyChanged("grupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int nivelBateria {
            get {
                return this.nivelBateriaField;
            }
            set {
                this.nivelBateriaField = value;
                this.RaisePropertyChanged("nivelBateria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
                this.RaisePropertyChanged("numeroSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public System.DateTime ultimaConexion {
            get {
                return this.ultimaConexionField;
            }
            set {
                this.ultimaConexionField = value;
                this.RaisePropertyChanged("ultimaConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ultimaConexionSpecified {
            get {
                return this.ultimaConexionFieldSpecified;
            }
            set {
                this.ultimaConexionFieldSpecified = value;
                this.RaisePropertyChanged("ultimaConexionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class aplicacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int aplicacionIdField;
        
        private categoriaAplicacion categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string desarrolladorField;
        
        private string descripcionField;
        
        private System.DateTime fechaLanzamientoField;
        
        private bool fechaLanzamientoFieldSpecified;
        
        private string nombreField;
        
        private string rutaInstaladorField;
        
        private double tamanoMBField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int aplicacionId {
            get {
                return this.aplicacionIdField;
            }
            set {
                this.aplicacionIdField = value;
                this.RaisePropertyChanged("aplicacionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public categoriaAplicacion categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string desarrollador {
            get {
                return this.desarrolladorField;
            }
            set {
                this.desarrolladorField = value;
                this.RaisePropertyChanged("desarrollador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaLanzamiento {
            get {
                return this.fechaLanzamientoField;
            }
            set {
                this.fechaLanzamientoField = value;
                this.RaisePropertyChanged("fechaLanzamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaLanzamientoSpecified {
            get {
                return this.fechaLanzamientoFieldSpecified;
            }
            set {
                this.fechaLanzamientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaLanzamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string rutaInstalador {
            get {
                return this.rutaInstaladorField;
            }
            set {
                this.rutaInstaladorField = value;
                this.RaisePropertyChanged("rutaInstalador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double tamanoMB {
            get {
                return this.tamanoMBField;
            }
            set {
                this.tamanoMBField = value;
                this.RaisePropertyChanged("tamanoMB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public enum categoriaAplicacion {
        
        /// <remarks/>
        EDUCATIVA,
        
        /// <remarks/>
        ENTRETENIMIENTO,
        
        /// <remarks/>
        TERAPEUTICA,
        
        /// <remarks/>
        ENTRENAMIENTO,
        
        /// <remarks/>
        PRODUCTIVIDAD,
        
        /// <remarks/>
        SIMULACION,
        
        /// <remarks/>
        MULTIMEDIA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class configuracion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int configuracionIdField;
        
        private usuario creadoPorField;
        
        private string descripcionField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private string nombreField;
        
        private tipoConfiguracion tipoField;
        
        private bool tipoFieldSpecified;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int configuracionId {
            get {
                return this.configuracionIdField;
            }
            set {
                this.configuracionIdField = value;
                this.RaisePropertyChanged("configuracionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public usuario creadoPor {
            get {
                return this.creadoPorField;
            }
            set {
                this.creadoPorField = value;
                this.RaisePropertyChanged("creadoPor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoConfiguracion tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private actividad[] actividadesField;
        
        private bool activoField;
        
        private string apellidoField;
        
        private string contrasenaField;
        
        private string correoField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private string nombreField;
        
        private rol rolField;
        
        private int usuarioIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actividades", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public actividad[] actividades {
            get {
                return this.actividadesField;
            }
            set {
                this.actividadesField = value;
                this.RaisePropertyChanged("actividades");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public rol rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class actividad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int actividadIdField;
        
        private bool activoField;
        
        private string descripcionField;
        
        private string detallesTecnicosField;
        
        private dispositivo dispositivoAfectadoField;
        
        private System.DateTime fechaHoraField;
        
        private bool fechaHoraFieldSpecified;
        
        private tipoActividad tipoActividadField;
        
        private bool tipoActividadFieldSpecified;
        
        private usuario usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int actividadId {
            get {
                return this.actividadIdField;
            }
            set {
                this.actividadIdField = value;
                this.RaisePropertyChanged("actividadId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string detallesTecnicos {
            get {
                return this.detallesTecnicosField;
            }
            set {
                this.detallesTecnicosField = value;
                this.RaisePropertyChanged("detallesTecnicos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public dispositivo dispositivoAfectado {
            get {
                return this.dispositivoAfectadoField;
            }
            set {
                this.dispositivoAfectadoField = value;
                this.RaisePropertyChanged("dispositivoAfectado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraSpecified {
            get {
                return this.fechaHoraFieldSpecified;
            }
            set {
                this.fechaHoraFieldSpecified = value;
                this.RaisePropertyChanged("fechaHoraSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoActividad tipoActividad {
            get {
                return this.tipoActividadField;
            }
            set {
                this.tipoActividadField = value;
                this.RaisePropertyChanged("tipoActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoActividadSpecified {
            get {
                return this.tipoActividadFieldSpecified;
            }
            set {
                this.tipoActividadFieldSpecified = value;
                this.RaisePropertyChanged("tipoActividadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public enum tipoActividad {
        
        /// <remarks/>
        INICIO_SESION,
        
        /// <remarks/>
        CIERRE_SESION,
        
        /// <remarks/>
        REGISTRO_DISPOSITIVO,
        
        /// <remarks/>
        ACTUALIZACION_FIRMWARE,
        
        /// <remarks/>
        INSTALACION_APLICACION,
        
        /// <remarks/>
        DESINSTALACION_APLICACION,
        
        /// <remarks/>
        CONFIGURACION_DISPOSITIVO,
        
        /// <remarks/>
        CAMBIO_ESTADO_DISPOSITIVO,
        
        /// <remarks/>
        ASIGNACION_GRUPO,
        
        /// <remarks/>
        CREACION_USUARIO,
        
        /// <remarks/>
        MODIFICACION_USUARIO,
        
        /// <remarks/>
        CREACION_GRUPO,
        
        /// <remarks/>
        MODIFICACION_GRUPO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class rol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private string nombreField;
        
        private int rolIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int rolId {
            get {
                return this.rolIdField;
            }
            set {
                this.rolIdField = value;
                this.RaisePropertyChanged("rolId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public enum tipoConfiguracion {
        
        /// <remarks/>
        AUDIO,
        
        /// <remarks/>
        VIDEO,
        
        /// <remarks/>
        CONTROL,
        
        /// <remarks/>
        RED,
        
        /// <remarks/>
        SEGURIDAD,
        
        /// <remarks/>
        SISTEMA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public enum estadoConexion {
        
        /// <remarks/>
        CONECTADO,
        
        /// <remarks/>
        DESCONECTADO,
        
        /// <remarks/>
        EN_USO,
        
        /// <remarks/>
        EN_MANTENIMIENTO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class firmware : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private dispositivo dispositivoField;
        
        private System.DateTime fechaLanzamientoField;
        
        private bool fechaLanzamientoFieldSpecified;
        
        private int firmwareIdField;
        
        private grupo grupoField;
        
        private string nombreField;
        
        private string rutaArchivoField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public dispositivo dispositivo {
            get {
                return this.dispositivoField;
            }
            set {
                this.dispositivoField = value;
                this.RaisePropertyChanged("dispositivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaLanzamiento {
            get {
                return this.fechaLanzamientoField;
            }
            set {
                this.fechaLanzamientoField = value;
                this.RaisePropertyChanged("fechaLanzamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaLanzamientoSpecified {
            get {
                return this.fechaLanzamientoFieldSpecified;
            }
            set {
                this.fechaLanzamientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaLanzamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int firmwareId {
            get {
                return this.firmwareIdField;
            }
            set {
                this.firmwareIdField = value;
                this.RaisePropertyChanged("firmwareId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public grupo grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
                this.RaisePropertyChanged("grupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string rutaArchivo {
            get {
                return this.rutaArchivoField;
            }
            set {
                this.rutaArchivoField = value;
                this.RaisePropertyChanged("rutaArchivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", ConfigurationName="DispositivosWS.DispositivoWS")]
    public interface DispositivoWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/listarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/listarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.DispositivosWS.Exception), Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/listarDispositivo/Fault/Exceptio" +
            "n", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.DispositivosWS.listarDispositivoResponse listarDispositivo(FrontVR.DispositivosWS.listarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/listarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/listarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.DispositivosWS.listarDispositivoResponse> listarDispositivoAsync(FrontVR.DispositivosWS.listarDispositivoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/obtenerDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/obtenerDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.DispositivosWS.Exception), Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/obtenerDispositivo/Fault/Excepti" +
            "on", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.DispositivosWS.obtenerDispositivoResponse obtenerDispositivo(FrontVR.DispositivosWS.obtenerDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/obtenerDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/obtenerDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.DispositivosWS.obtenerDispositivoResponse> obtenerDispositivoAsync(FrontVR.DispositivosWS.obtenerDispositivoRequest request);
        
        // CODEGEN: Parameter 'elemento' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/actualizarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/actualizarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.DispositivosWS.Exception), Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/actualizarDispositivo/Fault/Exce" +
            "ption", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.DispositivosWS.actualizarDispositivoResponse actualizarDispositivo(FrontVR.DispositivosWS.actualizarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/actualizarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/actualizarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.DispositivosWS.actualizarDispositivoResponse> actualizarDispositivoAsync(FrontVR.DispositivosWS.actualizarDispositivoRequest request);
        
        // CODEGEN: Parameter 'elemento' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/registrarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/registrarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.DispositivosWS.Exception), Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/registrarDispositivo/Fault/Excep" +
            "tion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.DispositivosWS.registrarDispositivoResponse registrarDispositivo(FrontVR.DispositivosWS.registrarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/registrarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/registrarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.DispositivosWS.registrarDispositivoResponse> registrarDispositivoAsync(FrontVR.DispositivosWS.registrarDispositivoRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/eliminarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/eliminarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.DispositivosWS.Exception), Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/eliminarDispositivo/Fault/Except" +
            "ion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.DispositivosWS.eliminarDispositivoResponse eliminarDispositivo(FrontVR.DispositivosWS.eliminarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/eliminarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/eliminarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.DispositivosWS.eliminarDispositivoResponse> eliminarDispositivoAsync(FrontVR.DispositivosWS.eliminarDispositivoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDispositivo", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarDispositivoRequest {
        
        public listarDispositivoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDispositivoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarDispositivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.DispositivosWS.dispositivo[] @return;
        
        public listarDispositivoResponse() {
        }
        
        public listarDispositivoResponse(FrontVR.DispositivosWS.dispositivo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDispositivo", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerDispositivoRequest() {
        }
        
        public obtenerDispositivoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDispositivoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerDispositivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.DispositivosWS.dispositivo @return;
        
        public obtenerDispositivoResponse() {
        }
        
        public obtenerDispositivoResponse(FrontVR.DispositivosWS.dispositivo @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarDispositivo", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class actualizarDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.DispositivosWS.dispositivo elemento;
        
        public actualizarDispositivoRequest() {
        }
        
        public actualizarDispositivoRequest(FrontVR.DispositivosWS.dispositivo elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarDispositivoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class actualizarDispositivoResponse {
        
        public actualizarDispositivoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarDispositivo", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class registrarDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.DispositivosWS.dispositivo elemento;
        
        public registrarDispositivoRequest() {
        }
        
        public registrarDispositivoRequest(FrontVR.DispositivosWS.dispositivo elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarDispositivoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class registrarDispositivoResponse {
        
        public registrarDispositivoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDispositivo", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class eliminarDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarDispositivoRequest() {
        }
        
        public eliminarDispositivoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDispositivoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class eliminarDispositivoResponse {
        
        public eliminarDispositivoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DispositivoWSChannel : FrontVR.DispositivosWS.DispositivoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DispositivoWSClient : System.ServiceModel.ClientBase<FrontVR.DispositivosWS.DispositivoWS>, FrontVR.DispositivosWS.DispositivoWS {
        
        public DispositivoWSClient() {
        }
        
        public DispositivoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DispositivoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DispositivoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DispositivoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.DispositivosWS.listarDispositivoResponse FrontVR.DispositivosWS.DispositivoWS.listarDispositivo(FrontVR.DispositivosWS.listarDispositivoRequest request) {
            return base.Channel.listarDispositivo(request);
        }
        
        public FrontVR.DispositivosWS.dispositivo[] listarDispositivo() {
            FrontVR.DispositivosWS.listarDispositivoRequest inValue = new FrontVR.DispositivosWS.listarDispositivoRequest();
            FrontVR.DispositivosWS.listarDispositivoResponse retVal = ((FrontVR.DispositivosWS.DispositivoWS)(this)).listarDispositivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.DispositivosWS.listarDispositivoResponse> FrontVR.DispositivosWS.DispositivoWS.listarDispositivoAsync(FrontVR.DispositivosWS.listarDispositivoRequest request) {
            return base.Channel.listarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.DispositivosWS.listarDispositivoResponse> listarDispositivoAsync() {
            FrontVR.DispositivosWS.listarDispositivoRequest inValue = new FrontVR.DispositivosWS.listarDispositivoRequest();
            return ((FrontVR.DispositivosWS.DispositivoWS)(this)).listarDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.DispositivosWS.obtenerDispositivoResponse FrontVR.DispositivosWS.DispositivoWS.obtenerDispositivo(FrontVR.DispositivosWS.obtenerDispositivoRequest request) {
            return base.Channel.obtenerDispositivo(request);
        }
        
        public FrontVR.DispositivosWS.dispositivo obtenerDispositivo(int id) {
            FrontVR.DispositivosWS.obtenerDispositivoRequest inValue = new FrontVR.DispositivosWS.obtenerDispositivoRequest();
            inValue.id = id;
            FrontVR.DispositivosWS.obtenerDispositivoResponse retVal = ((FrontVR.DispositivosWS.DispositivoWS)(this)).obtenerDispositivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.DispositivosWS.obtenerDispositivoResponse> FrontVR.DispositivosWS.DispositivoWS.obtenerDispositivoAsync(FrontVR.DispositivosWS.obtenerDispositivoRequest request) {
            return base.Channel.obtenerDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.DispositivosWS.obtenerDispositivoResponse> obtenerDispositivoAsync(int id) {
            FrontVR.DispositivosWS.obtenerDispositivoRequest inValue = new FrontVR.DispositivosWS.obtenerDispositivoRequest();
            inValue.id = id;
            return ((FrontVR.DispositivosWS.DispositivoWS)(this)).obtenerDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.DispositivosWS.actualizarDispositivoResponse FrontVR.DispositivosWS.DispositivoWS.actualizarDispositivo(FrontVR.DispositivosWS.actualizarDispositivoRequest request) {
            return base.Channel.actualizarDispositivo(request);
        }
        
        public void actualizarDispositivo(FrontVR.DispositivosWS.dispositivo elemento) {
            FrontVR.DispositivosWS.actualizarDispositivoRequest inValue = new FrontVR.DispositivosWS.actualizarDispositivoRequest();
            inValue.elemento = elemento;
            FrontVR.DispositivosWS.actualizarDispositivoResponse retVal = ((FrontVR.DispositivosWS.DispositivoWS)(this)).actualizarDispositivo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.DispositivosWS.actualizarDispositivoResponse> FrontVR.DispositivosWS.DispositivoWS.actualizarDispositivoAsync(FrontVR.DispositivosWS.actualizarDispositivoRequest request) {
            return base.Channel.actualizarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.DispositivosWS.actualizarDispositivoResponse> actualizarDispositivoAsync(FrontVR.DispositivosWS.dispositivo elemento) {
            FrontVR.DispositivosWS.actualizarDispositivoRequest inValue = new FrontVR.DispositivosWS.actualizarDispositivoRequest();
            inValue.elemento = elemento;
            return ((FrontVR.DispositivosWS.DispositivoWS)(this)).actualizarDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.DispositivosWS.registrarDispositivoResponse FrontVR.DispositivosWS.DispositivoWS.registrarDispositivo(FrontVR.DispositivosWS.registrarDispositivoRequest request) {
            return base.Channel.registrarDispositivo(request);
        }
        
        public void registrarDispositivo(FrontVR.DispositivosWS.dispositivo elemento) {
            FrontVR.DispositivosWS.registrarDispositivoRequest inValue = new FrontVR.DispositivosWS.registrarDispositivoRequest();
            inValue.elemento = elemento;
            FrontVR.DispositivosWS.registrarDispositivoResponse retVal = ((FrontVR.DispositivosWS.DispositivoWS)(this)).registrarDispositivo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.DispositivosWS.registrarDispositivoResponse> FrontVR.DispositivosWS.DispositivoWS.registrarDispositivoAsync(FrontVR.DispositivosWS.registrarDispositivoRequest request) {
            return base.Channel.registrarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.DispositivosWS.registrarDispositivoResponse> registrarDispositivoAsync(FrontVR.DispositivosWS.dispositivo elemento) {
            FrontVR.DispositivosWS.registrarDispositivoRequest inValue = new FrontVR.DispositivosWS.registrarDispositivoRequest();
            inValue.elemento = elemento;
            return ((FrontVR.DispositivosWS.DispositivoWS)(this)).registrarDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.DispositivosWS.eliminarDispositivoResponse FrontVR.DispositivosWS.DispositivoWS.eliminarDispositivo(FrontVR.DispositivosWS.eliminarDispositivoRequest request) {
            return base.Channel.eliminarDispositivo(request);
        }
        
        public void eliminarDispositivo(int id) {
            FrontVR.DispositivosWS.eliminarDispositivoRequest inValue = new FrontVR.DispositivosWS.eliminarDispositivoRequest();
            inValue.id = id;
            FrontVR.DispositivosWS.eliminarDispositivoResponse retVal = ((FrontVR.DispositivosWS.DispositivoWS)(this)).eliminarDispositivo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.DispositivosWS.eliminarDispositivoResponse> FrontVR.DispositivosWS.DispositivoWS.eliminarDispositivoAsync(FrontVR.DispositivosWS.eliminarDispositivoRequest request) {
            return base.Channel.eliminarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.DispositivosWS.eliminarDispositivoResponse> eliminarDispositivoAsync(int id) {
            FrontVR.DispositivosWS.eliminarDispositivoRequest inValue = new FrontVR.DispositivosWS.eliminarDispositivoRequest();
            inValue.id = id;
            return ((FrontVR.DispositivosWS.DispositivoWS)(this)).eliminarDispositivoAsync(inValue);
        }
    }
}
