# Configuracion para MySQL
db.type=mysql
mysql.jdbcUrl=jdbc:mysql://dbprog3.ctcqo6ic8a8d.us-east-1.rds.amazonaws.com:3306/prog3G?allowPublicKeyRetrieval=true&useSSL=false
mysql.username=admin
mysql.password=pucp123456#

# Configuracion del pool de conexiones
db.minIdle=5
db.maxPoolSize=10
db.connectionTimeout=20000
db.idleTimeout=100000